#166214082 Database setup
KvNGCzA/Hello-Books-BE pull request #11
Opened 2019-05-28 14:36 UTC by Ukhu

#### Description
Sets up Postgresql database and Sequelize.js ORM

#### Type of change
 - Install 'sequelize', 'sequelize-cli', 'pg' and 'pg-hstore' packages
 - Add .sequelizerc file
 - Bootstrap project using Sequelize-CLI to create necessary folders including; config, migrations, seeders, and models
 - Update default config file to use environment variables of the project
 - Add .env.sample file

#### How Has This Been Tested?
I tested the setup locally by using the Sequelize CLI to create a table in the database and populate it using dummy data from the seeding process.

#### Checklist:
N/A

#### Pivotal Tracker
#166214082

2019-05-28 17:55 UTC, KvNGCzA requested changes

2019-05-28 17:55 UTC, KvNGCzA commented on server/database/config/config.js
> +};
Add a new line here

2019-05-28 18:30 UTC, KvNGCzA requested changes

2019-05-28 18:30 UTC, KvNGCzA commented on server/database/config/config.js
> +    use_env_variable: 'DATABASE_URL'
Add `dialect: 'postgres'` here

2019-05-28 18:30 UTC, KvNGCzA commented on server/database/config/config.js
> +    port: 5432,
make port equals `process.env.DB_PORT`

2019-05-28 18:30 UTC, KvNGCzA commented on server/database/config/config.js
> +    host: '127.0.0.1',
make host equals `process.env.DB_HOST`

2019-05-28 19:40 UTC, Lundii reviewed
I ran npx sequelize-cli init 
but I'm getting path must be a string error

2019-05-28 19:55 UTC, Ukhu commented
> I ran npx sequelize-cli init
> but I'm getting path must be a string error

You're not supposed to run the 'npx sequelize-cli init' command again. That's basically like starting over the work I've done already.

2019-05-28 20:14 UTC, KvNGCzA commented on package.json
> +        "migrations": "npx sequelize db:migrate"
Remove this migration script and add the following
````
"db:rollback": "npm run db:back && npm run db:roll && npm run db:seed",
"db:roll": "sequelize db:migrate",
"db:back": "sequelize db:migrate:undo:all",
"db:seed": "sequelize db:seed:all"
````

2019-05-28 20:21 UTC, Lundii commented
> > I ran npx sequelize-cli init
> > but I'm getting path must be a string error
> 
> You're not supposed to run the 'npx sequelize-cli init' command again. That's basically like starting over the work I've done already.

I ran the script using --force flag and it worked. I reverted the changes though.
I was able to create migrations, run it, create a database, create seeds and added seeds to my database using the link you gave me http://docs.sequelizejs.com/manual/migrations.html


I've not used sequelize before now but I guess these are the basic things to show that the configuration is working.

2019-05-28 20:21 UTC, Lundii approved these changes

2019-05-29 02:58 UTC, KvNGCzA approved these changes

2019-05-29 03:44 UTC, allebd approved these changes
Good

2019-05-29 06:22 UTC, Nennyfills approved these changes

2019-05-29 06:23 UTC, Nennyfills approved these changes
good job

2019-05-29 08:26 UTC, merged