FT=166313415-roles (model): roles model
KvNGCzA/Hello-Books-BE pull request #15
Opened 2019-05-29 20:03 UTC by oluwajhay

#### What does this PR do?
Create roles model
#### Description of Task to be completed?
-create roles model
-create admin roles seeder file
-create patron roles seeder file
#### How should this be manually tested?
clone or download the project
checkout to ft=create-roles-model-166313415
git pull to get the latest update
npm i to install dependencies
create a database
npm run db:seed to test the feature
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166313415](https://www.pivotaltracker.com/n/projects/2350588/stories/166313415)

#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-05-29 21:11 UTC, allebd commented
Your commit PR title is not using the right convention specified

2019-05-30 01:01 UTC, Adekoreday commented on server/database/seeders/20190529165259-patron.js
> +  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('roles', null, {})
the task is meant to create models alone do not include migration and seed files

2019-05-30 01:03 UTC, Adekoreday commented on server/database/seeders/20190529165259-patron.js
> +  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('roles', [{
avoid use of fat arrow functions es5 was recommended by TTL here

2019-05-30 01:12 UTC, Adekoreday requested changes
you need to add roles associations there exist a relation between roles and userRoles in your role model

2019-05-30 14:56 UTC, Adekoreday requested changes
change the typre from ft in your commit message

2019-05-30 15:00 UTC, allebd reviewed
Join your seeders file together as an array, you should have one seed file, not two

2019-05-30 15:06 UTC, oluwajhay commented
> Join your seeders file together as an array, you should have one seed file, not two

I have just one seeder file

2019-05-30 15:45 UTC, Adekoreday requested changes
the above is on develop

2019-05-30 16:15 UTC, Lundii requested changes
* You should add `/* eslint-disable */ ` in all your migrations, models and seeders file as started by the TTL

2019-05-30 16:29 UTC, Lundii commented
> ![image](https://user-images.githubusercontent.com/44194416/58644711-bfeda180-82f9-11e9-9ca7-e37061c75b16.png)
> 
> the above is on develop
> 
> the one below is on your branch it might cause some conflicts i think you need to resolve this
> ![image](https://user-images.githubusercontent.com/44194416/58644924-38546280-82fa-11e9-84b9-e4530ce22cee.png)

Korede, please fetch his branch again. There is just one single seeders file

2019-05-30 18:56 UTC, closed without merging