#166324980 Creates fines model
KvNGCzA/Hello-Books-BE pull request #22
Opened 2019-05-31 12:45 UTC by Lundii

#### What does this PR do?
It creates a model for storing fines
#### Description of Task to be completed?
* created a migration file for the fines model
#### How should this be manually tested?
* git pull or fetch this branch
* run npm install to get all dependencies
* run npm run db:roll to create the model
* confirm the model is created in you db
#### Any background context you want to provide?
No
#### What are the relevant pivotal tracker stories?
[#166324980](https://www.pivotaltracker.com/story/show/166324980)
#### Screenshots (if appropriate)
No
#### Questions:
No

2019-05-31 13:31 UTC, henryade requested changes
I cant see price in your models file.

2019-05-31 14:47 UTC, Lundii commented
> I cant see price in your models file.

Done

2019-05-31 15:03 UTC, allebd requested changes
No association of fines to users in the user model

No association of fines to book in the book model

2019-05-31 15:17 UTC, Lundii commented
> No association of fines to users in the user model
> 
> No association of fines to book in the book model

Done

2019-05-31 16:11 UTC, Ukhu commented on server/database/models/books.js
> +      as: 'id'
Remove the 'as' property. Just specify the foreign key and the onDelete constraint here.

2019-05-31 16:16 UTC, Ukhu commented on server/database/models/fines.js
> +      foreignKey: 'id',
The 'foreignKey' here is the 'userId' not 'id'.

2019-05-31 16:16 UTC, Ukhu commented on server/database/models/fines.js
> +      sourceKey: 'userId',
No need for 'sourceKey' here

2019-05-31 16:17 UTC, Ukhu commented on server/database/models/fines.js
> +      foreignKey: 'id',
The 'foreignKey' here is the 'bookId' not 'id'.

2019-05-31 16:17 UTC, Ukhu commented on server/database/models/fines.js
> +      sourceKey: 'bookId',
No need for 'sourceKey' here

2019-05-31 16:19 UTC, Ukhu commented on server/database/models/users.js
> +      as: 'id'
Specify the 'foreignKey' and the 'onDelete' constraint. No need for 'as' here.

2019-05-31 16:21 UTC, Ukhu requested changes
Rebase branch

2019-05-31 16:51 UTC, Ukhu commented on server/database/migrations/20190530001212-create-fines.js
> +        allowNull: false,
Add 'onDelete' constraint.

2019-05-31 16:52 UTC, Ukhu commented on server/database/migrations/20190530001212-create-fines.js
> +        allowNull: false,
Add 'onDelete' constraint.

2019-05-31 16:54 UTC, Ukhu commented on server/database/models/users.js
>      });
Add spacing here.

2019-05-31 18:17 UTC, Ukhu submitted a review, later dismissed

2019-05-31 18:36 UTC, allebd commented
Kindly work on your commit messages, it is not following the right convention

2019-05-31 19:39 UTC, Lundii commented
> Kindly work on your commit message, it is not following the right convention, don't forget to use imperative and present tense on your header and body message

Done

2019-05-31 19:52 UTC, Ukhu submitted a review, later dismissed

2019-05-31 20:11 UTC, henryade submitted a review, later dismissed

2019-05-31 22:11 UTC, Nennyfills submitted a review, later dismissed
Nice

2019-05-31 23:12 UTC, KvNGCzA requested changes
There are issues with your associations. Please look into them

2019-06-01 08:50 UTC, Lundii commented
> There are issues with your associations. Please look into them

Fixed

2019-06-01 14:12 UTC, merged