#166374546 Add lendingHistory model
KvNGCzA/Hello-Books-BE pull request #27
Opened 2019-05-31 23:14 UTC by Adekoreday

#### What does this PR do?

create lendingHistory model,
add lendingHistory migrations,

#### Description of Task to be completed?
N/A
#### How should this be manually tested?
```
clone or download repository
npm run install
add .env file
include PORT and database parameters in the .env file.
```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#166374546
#### Screenshots (if appropriate)

#### Questions:

2019-06-01 13:18 UTC, KvNGCzA requested changes
Rebase your branch
done

2019-06-01 13:18 UTC, KvNGCzA commented on server/database/models/users.js
> +      Users.hasMany(models.lendingHistory, {
When you rebase, please ensure to correct this

2019-06-01 14:23 UTC, KvNGCzA commented on server/database/migrations/20190531184608-create-lending-history.js
> +  },
Shouldn't this table also have bookId, date it was borrowed and date it was be returned?

2019-06-02 01:35 UTC, allebd commented on server/database/models/lendinghistory.js
> +    duration: DataTypes.STRING
You did not define userId and bookId

2019-06-02 10:56 UTC, KvNGCzA requested changes

2019-06-02 10:56 UTC, KvNGCzA commented on server/database/migrations/20190531184608-create-lending-history.js
> +    return queryInterface.createTable('lendingHistories', {
Why is your table named in Camel Case?

2019-06-02 10:56 UTC, KvNGCzA commented on server/database/migrations/20190531184608-create-lending-history.js
> +         duration: {
fix your indentation

2019-06-02 14:57 UTC, Adekoreday commented on server/database/migrations/20190531184608-create-lending-history.js
> +    return queryInterface.createTable('lendingHistories', {
will reflect on this just seeing it

2019-06-02 14:57 UTC, Adekoreday commented on server/database/migrations/20190531184608-create-lending-history.js
> +         duration: {
thanks will reflect on this

2019-06-02 20:27 UTC, Lundii submitted a review, later dismissed
Good

2019-06-02 21:56 UTC, allebd commented on server/database/models/book.js
> +   Book.hasMany(models.Fine, {
Kindly work on your indentation

2019-06-02 21:56 UTC, allebd commented on server/database/models/book.js
> +  Book.hasMany(models.Lendinghistory, {
Kindly work on this indentation also

2019-06-02 22:10 UTC, KvNGCzA requested changes

2019-06-02 22:10 UTC, KvNGCzA commented on server/database/models/book.js
> +  Book.hasMany(models.Lendinghistory, {
`LendingHistory`

2019-06-02 22:26 UTC, Adekoreday commented on server/database/models/book.js
> +  Book.hasMany(models.Lendinghistory, {
thanks will do

2019-06-02 22:26 UTC, Adekoreday commented on server/database/models/book.js
> +  Book.hasMany(models.Lendinghistory, {
ok will change it

2019-06-03 01:09 UTC, KvNGCzA approved these changes

2019-06-03 01:10 UTC, merged