#166395293 creates login route
KvNGCzA/Hello-Books-BE pull request #30
Opened 2019-06-01 22:15 UTC by Lundii

- add login route

[Starts #166395293]

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-06-02 15:19 UTC, allebd commented
Your PR message is wrong

2019-06-02 22:16 UTC, allebd commented on server/controllers/homeController.js
> +    User.findOne({ where: { email: req.body.email } }).then((result) => {
Deconstruct your objects and use async/await instead of .then

2019-06-02 22:16 UTC, allebd commented on server/controllers/homeController.js
> +        verifypassword = helpers.comparePassword(req.body.password, user.password);
Deconstruct your objects

2019-06-02 22:16 UTC, allebd commented on server/controllers/homeController.js
> +        return res.status(403).json({ status: 'failure', error: 'username or password is incorrect' });
Make use of the responseMessage helper function

2019-06-02 22:16 UTC, allebd commented on server/routes/index.js
> +}
Newline required at the end of file

2019-06-02 22:16 UTC, allebd commented on test/login-test.js
> +  before(function (done) {
use es6 function

2019-06-02 22:16 UTC, allebd commented on test/login-test.js
> +  after(function (done) {
use es6 function

2019-06-03 22:09 UTC, allebd commented on server/controllers/authController.js
> +class AuthController {
Your file name and class name are not the same

2019-06-03 22:09 UTC, allebd commented on server/controllers/authController.js
> +   * @param {object} request - the requestuest object
requestest object in comment

2019-06-03 22:09 UTC, allebd commented on server/controllers/authController.js
> + * Home controller class
Home controller in comment

2019-06-03 22:09 UTC, allebd commented on server/routes/index.js
> +router.use('/auth', auth);
No api version indicated

2019-06-03 22:09 UTC, allebd commented on test/server/routes/login.test.js
> +import server from '../../../server/index';
No need for the index after server

2019-06-03 22:09 UTC, allebd commented on test/server/routes/login.test.js
> +  it('returns a status 200 if user supplies the right email and password', (done) => {
I think "valid email and password" sound better, instead of the "right email and password"

2019-06-03 22:10 UTC, henryade reviewed
The file name should be AuthController not authController. Then why did you name the test login.test.js?

2019-06-03 22:22 UTC, allebd commented
Kindly update the swagger documentation for your route accordingly

2019-06-04 00:13 UTC, Lundii commented
> The file name should be AuthController not authController. Then why did you name the test login.test.js?

If you look at the controller folder on the develop branch, there is a userController and I followed the convention. As for the test naming, I also followed the convention on the develop branch. Check, you will see a user.test.js file

2019-06-04 00:25 UTC, Lundii commented
> Kindly update the swagger documentation for your route accordingly

Done

2019-06-04 14:06 UTC, henryade reviewed
You have conflicting files and you haven't implemented any feedback

2019-06-04 14:08 UTC, henryade commented
> > The file name should be AuthController not authController. Then why did you name the test login.test.js?
> 
> If you look at the controller folder on the develop branch, there is a userController and I followed the convention. As for the test naming, I also followed the convention on the develop branch. Check, you will see a user.test.js file

but the right way by the TTL is the file name should be the same as the class.

2019-06-04 14:28 UTC, Lundii commented on server/routes/index.js
> +router.use('/auth', auth);
> No api version indicated

This is going to be included in the index file

2019-06-04 14:31 UTC, Lundii commented
> You have conflicting files and you haven't implemented any feedback

I'm seeing Bella's feedback now. Will resolve them

2019-06-04 14:37 UTC, Lundii commented on server/routes/index.js
> +router.use('/auth', auth);
> > No api version indicated
> 
> This is going to be included in the index.js file and not from my route

2019-06-04 16:11 UTC, Lundii commented
> You have conflicting files and you haven't implemented any feedback

Done

2019-06-04 16:11 UTC, Lundii commented
> You have conflicting files and you haven't implemented any feedback

Done

2019-06-04 16:52 UTC, KvNGCzA requested changes
Please rebase your branch. Add the login validator to your route and test.

2019-06-04 18:41 UTC, KvNGCzA requested changes

2019-06-04 18:41 UTC, KvNGCzA commented on package.json
>      "test": "npm run db:roll && npm run db:seed && nyc mocha --recursive test --timeout 10000 -r esm --exit && npm run db:back",
There are two heroku-postbuild scripts here

2019-06-04 18:41 UTC, KvNGCzA commented on server/controllers/AuthController.js
> +      const token = createToken({ id }, '2h');
This token should not expire

2019-06-04 19:11 UTC, Lundii commented on package.json
>      "test": "npm run db:roll && npm run db:seed && nyc mocha --recursive test --timeout 10000 -r esm --exit && npm run db:back",
> There are two heroku-postbuild scripts here

Resolved

2019-06-04 19:11 UTC, Lundii commented on server/controllers/AuthController.js
> +      const token = createToken({ id }, '2h');
> This token should not expire

Resolve

2019-06-04 19:38 UTC, KvNGCzA approved these changes

2019-06-04 19:38 UTC, merged