166457882-fix(bug fix): removes delete field
KvNGCzA/Hello-Books-BE pull request #37
Opened 2019-06-04 22:46 UTC by Lundii

#### What does this PR do?
It deletes the password field sent to the client when a user logs in
#### Description of Task to be completed?
* modified the AuthContoller file
#### How should this be manually tested?
* login as a registered user
* the password field is not returned as part of the returned object
#### Any background context you want to provide?
No
#### What are the relevant pivotal tracker stories?
[#166457882](https://www.pivotaltracker.com/story/show/166457882)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/37886814/58918610-d1341500-8722-11e9-9637-1f3e9aba88a2.png)

#### Questions:
No

2019-06-04 22:51 UTC, henryade reviewed
Correct the PR name

2019-06-04 22:53 UTC, KvNGCzA requested changes

2019-06-04 22:53 UTC, KvNGCzA commented on server/controllers/AuthController.js
> +        user: { ...dataValues, token }
take token out of the user object

2019-06-04 23:11 UTC, Lundii commented
> Correct the PR name

Done

2019-06-04 23:15 UTC, henryade commented
> > Correct the PR name
> 
> Done

Should the PR be named removes password field?

2019-06-04 23:17 UTC, Lundii commented
> > > Correct the PR name
> > 
> > 
> > Done
> 
> Should the PR be named removes password field?

Please suggest one for me

> > > Correct the PR name
> > 
> > 
> > Done
> 
> Should the PR be named removes password field?

Corrected

2019-06-05 00:23 UTC, KvNGCzA approved these changes

2019-06-05 00:24 UTC, merged