166468649 Fix Validation Issues
KvNGCzA/Hello-Books-BE pull request #40
Opened 2019-06-05 16:31 UTC by Ukhu

#### What does this PR do?
Implement the validation changes raised during team pre-demo call

#### Description of Task to be completed?
  - handle more validation cases

#### How should this be manually tested?
  - pull this branch
  - run `npm test`
  - open Postman and test the validations on the signup route

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166468649](https://www.pivotaltracker.com/story/show/166468649)

#### Screenshots (if appropriate)
![Screenshot (158)](https://user-images.githubusercontent.com/35268825/58973298-8adcc580-87b7-11e9-9b5a-2be38822938d.png)

#### Questions:
N/A

2019-06-05 18:09 UTC, KvNGCzA requested changes
Write tests to cover the new cases you just added.

2019-06-05 19:46 UTC, Lundii reviewed
Can you add the new validations you added in the PR so we know exactly what we are testing for.

2019-06-05 20:36 UTC, Ukhu commented
> Write tests to cover the new cases you just added.

Done

2019-06-05 20:37 UTC, Ukhu commented
> Can you add the new validations you added in the PR so we know exactly what we are testing for.

Alright. Done that

2019-06-05 21:52 UTC, Lundii reviewed
Working fine. Please rebase so I approve

2019-06-05 22:06 UTC, Ukhu commented
> Working fine. Please rebase so I approve

Done

2019-06-05 22:18 UTC, allebd commented on server/middlewares/UserValidator.js
> +      .matches(/^[A-Za-z]+([ ]?|[-]?)[A-Za-z]+$/, 'g')
What of for names like Shaquille **O'Neal** can that be valid

2019-06-05 22:30 UTC, Lundii submitted a review, later dismissed

2019-06-07 04:26 UTC, allebd submitted a review, later dismissed
Nice Work

2019-06-07 16:53 UTC, henryade submitted a review, later dismissed

2019-06-07 17:51 UTC, KvNGCzA approved these changes

2019-06-07 17:53 UTC, merged