166214160-story(api): user can see borrowing stats
KvNGCzA/Hello-Books-BE pull request #54
Opened 2019-06-14 10:03 UTC by Lundii

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-06-15 12:21 UTC, Adekoreday requested changes
in your test you only need to login once and start using such login token and details , logining in several time will slow down the test overall test and may in the long run leading to us extending test timeouts

2019-06-15 19:24 UTC, Lundii commented
> in your test you only need to login once and start using such login token and details , logining in several time will slow down the test overall test and may in the long run leading to us extending test timeouts

If you look at the tests carefully, you will observe that I'm logging in different people and they are logged in only once.

2019-06-17 07:54 UTC, Ukhu reviewed
From your screenshot, the data returned in the borrowing history does not contain the name of the author for each book.

2019-06-18 07:17 UTC, Lundii commented
> From your screenshot, the data returned in the borrowing history does not contain the name of the author for each book.

Done

2019-06-19 09:38 UTC, KvNGCzA requested changes
This route should be `/user/lendinghistroy`

2019-06-19 12:15 UTC, Lundii commented
> This route should be `/user/lendinghistroy`

Done

2019-06-20 03:41 UTC, Nennyfills commented on server/controllers/BookController.js
> +        return responseMessage(response, 200, { status: 'success', dataValues });
your response should include count, number of pages and current page

2019-06-20 03:49 UTC, Nennyfills requested changes
your pagination responses should include count, current page and the number of pages.

2019-06-20 06:37 UTC, closed without merging

2019-06-20 07:26 UTC, Lundii commented
I realized this PR was closed. I may have mistakenly closed it. I presently cannot reopen it. I will open a new PR now.