166214111 edit user profile
KvNGCzA/Hello-Books-BE pull request #56
Opened 2019-06-14 16:11 UTC by oluwajhay

#### What does this PR do?
edit user profile
#### Description of Task to be completed?
- Create endpoint to edit user profile
#### How should this be manually tested?
- Clone or download the project 
- Run npm Install to install dependencies
- Run npm run db:rollback
- Start server and test manually with npm run start:dev
- Open postman, use
   http://localhost:{PORT}/api/v1/update`   
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166214111 ](https://www.pivotaltracker.com/story/show/166214111)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-06-15 09:20 UTC, Lundii approved these changes
Good job

2019-06-15 09:25 UTC, Lundii requested changes
Compare your swagger docs file with the one in develop, you removed from routes already there.

2019-06-15 22:34 UTC, Adekoreday requested changes
kindly rebase so we can continue review

2019-06-18 01:07 UTC, Ukhu commented on swagger.json
> +    }, "update": {
Why are you adding an 'update' request documentation to the _/auth/login_ route?

2019-06-18 01:24 UTC, Ukhu commented on server/routes/user.js
> +const UPDATE_BASE_URL = '/update';
Following REST guidelines, the correct URL for this route should be something like _/user/:userId_ since it is a particular user we are updating.

2019-06-18 01:28 UTC, Ukhu commented on swagger.json
> +      "required": [
These properties _email_, _firstName_, _lastName_, _password_ are optional. They shouldn't be required compulsorily. A user should be able to include only firstName OR email OR lastName. They don't have to provide all at once

2019-06-18 01:51 UTC, Ukhu requested changes
Well done on your work so far, however, here are my observations which I think should be addressed;

1) The URL for the update profile route does not follow REST guidelines

2) The current implementation that you have done is enforcing that users MUST provide _firstName_, _lastName_, _email_, AND _password_. This shouldn't be so. The user should be allowed to provide only the fields that they want to update.

3) Your implementation doesn't cater for cases where there are no values in the request body.

4) Your implementation doesn't cater for cases where a user tries to update their email with an already existent email.

5) With your current implementation, users can change their password directly from here. This shouldn't be so. The user should only be able to change their password through the reset password route.

**Recommendations;**

1) Regarding the URL, I think a correct one should be something like _/user/:userId_ since it is a particular user we are updating.

2) You can make the validations optional for the different fields so that it's only when a user provides them that express-validator will validate them.

3) You can check the request body to see if 'password' is among the fields provided, and then return an appropriate error message. You can also check if no values were provided at all in the request body and then return an appropriate message.

4) You can check if an email is provided in the body, and then query the database to see if it already exists.

2019-06-18 04:23 UTC, allebd commented on server/middlewares/UserValidator.js
> +  static updateValidation() {
The validation name seems unclear, kindly rename to maybe profileValidation

2019-06-18 23:27 UTC, Ukhu approved these changes

2019-06-19 08:02 UTC, Lundii approved these changes

2019-06-19 09:04 UTC, KvNGCzA approved these changes

2019-06-19 09:05 UTC, merged